# Path to the working directory where the repository was cloned
repo_folder: "path/to/epigeneticbutton/repo"

# Name of analysis
analysis_name: "test_snakemake"

# Path to the sample metadata file
sample_file: "samples.tsv"

# Path to the directory containing reference genomes
ref_path: "path/to/reference/genomes"

# Read quality parameters: 
# default of quality>10 and minimum read length 20nt
trimming_quality: "-q 10 -m 20"

# Mapping option default
chip_mapping_option: "default"

# ChIP-seq parameters
chip_mapping:
  default:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeat:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeatall:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -F 256"
  all:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end "
    filter: "-b -h -F 256"

# RNA parameters
rna_bedgraph:
  RNA:
    param_bg: "--outWigType bedGraph"
    strandedness: "reverse"
  RAMPAGE:
    param_bg: "--outWigType bedGraph read1_5p"
    strandedness: "forward"

# Analysis parameters
analysis:
  mark_of_interest: "H3K27ac"  # Default histone mark to focus on
  perform_analysis: true       # Whether to perform the complete analysis
  perform_combined: true       # Whether to perform combined analysis per line
  perform_heatmaps: true       # Whether to generate heatmaps with deeptools
  perform_te_analysis: false   # Whether to perform TE analysis (takes long time)

# Resource allocation
resources:
  threads: 8
  memory: "16G"
  tmp_space: "10G" 