# Path to the working directory where the repository was cloned
repo_folder: /grid/martienssen/home/jcahn/nlsas/projects/epibutton
repo_folder_rule: "path/to/epigeneticbutton/repo"

# Name of analysis
analysis_name: "test_snakemake"

# Path to the sample metadata file
sample_file: "samples.tsv"

# Path to the directory containing reference genomes
ref_path: "/grid/martienssen/home/jcahn/nlsas/Genomes/Arabidopsis"
ref_path_rule: "path/to/reference/genomes"

# Read quality parameters: 
# default of quality>10 and minimum read length 20nt
trimming_quality: "-q 10 -m 20"

# Mapping option default
chip_mapping_option: "default"

# ChIP-seq parameters
# For mapping
chip_mapping:
  default:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeat:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeatall:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -F 256"
  all:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end "
    filter: "-b -h -F 256"

# For bigwigs
chip_tracks:
  binsize: 1
  params: "--scaleFactorsMethod 'None' --normalizeUsing CPM --extendReads 300"

# ChIP plots option: default = "all", returns all plots (fingerprints, reports). Replace with "none" if you don't want anything.
QC_option: "all"

# For peaks
chip_callpeaks:
  # To link the type of IP with the type of peaks. Can be updated with other marks. If creating regex patterns, make sure to escape "." with "\."
  peaktype:
    'H3K4me1|H3K27me1|H3K27me2|H3K27me3|H3K9me1|H3K9me2|H3K9me3|H4K20me1|H4K20me2|H4K20me3|.*DDM1|H3\.3|H3\.1|MGH3|CenH3|PolIIS2P|H2AT120Ph|H2AKub|H3K36me3': "broad"
    'H3K27ac|H3K4me3|H3K9ac|H4K16ac|H3K23ac|MNase': "narrow"
    'H3|H4': "broad"
  params: "--keep-dup 'all' --nomodel"
  # For Arabidopsis, use 1.3e8; For maize, 2.2e9
  genomesize: "1.3.e8"
  
# For Arabidopsis, use 12; For maize, 14 (bowtie2 default) is best
star_index: "--genomeSAindexNbases 12"

# RNA parameters
rna_tracks:
  RNAseq:
    param_bg: "--outWigType bedGraph"
    strandedness: "reverse"
  RAMPAGE:
    param_bg: "--outWigType bedGraph read1_5p"
    strandedness: "forward"

# Analysis parameters
analysis:
  mark_of_interest: "H3K27ac"  # Default histone mark to focus on
  perform_analysis: true       # Whether to perform the complete analysis
  perform_combined: true       # Whether to perform combined analysis per line
  perform_heatmaps: true       # Whether to generate heatmaps with deeptools
  perform_te_analysis: false   # Whether to perform TE analysis (takes long time)

# Resource allocation
resources:
  threads: 8
  memory: "16G"
  tmp_space: "10G" 