# Path to the working directory where the repository was cloned
repo_folder: "/grid/martienssen/home/jcahn/nlsas/projects/testmC"
repo_folder_rule: "path/to/epigeneticbutton/repo"

# Name of the run
analysis_name: "test_snakemake"

# To perform the whole analysis
full_analysis: true

# Path to the sample metadata file
sample_file: "samples.tsv"

# Path to the directory containing reference genomes
ref_path: "/grid/martienssen/home/jcahn/nlsas/Genomes/Arabidopsis"
ref_path_rule: "path/to/reference/genomes"

# Read quality parameters: 
# default of quality>10 and minimum read length 20nt
trimming_quality: "-q 10 -m 20"

# Species-dependent parameters:
species: "maize"

arabidopsis:
  star_index: "--genomeSAindexNbases 12"
  genomesize: 1.3e8
maize: 
  star_index: "--genomeSAindexNbases 14"
  genomesize: 2.2e9

# Mapping option default
chip_mapping_option: "default"

# ChIP-seq parameters
# For mapping
chip_mapping:
  default:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeat:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeatall:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -F 256"
  all:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end "
    filter: "-b -h -F 256"

# For bigwigs
chip_tracks:
  binsize: 1
  params: "--scaleFactorsMethod 'None' --normalizeUsing CPM --extendReads 300"

# Output options: "all": returns all QC, stats, plots and files (i.e fastqc, fingerprints, idr, stats table and plots); "none" if you don't want the fastqc; other options can be added.
# QC_option: "all"
QC_option: "none"

# For peaks
chip_callpeaks:
  # To link the type of IP with the type of peaks. Can be updated with other marks. If creating regex patterns, make sure to escape "." with "\."
  peaktype:
    'H3K4me1|H3K27me1|H3K27me2|H3K27me3|H3K9me1|H3K9me2|H3K9me3|H4K20me1|H4K20me2|H4K20me3|.*DDM1|H3\.3|H3\.1|MGH3|CenH3|PolIIS2P|H2AT120Ph|H2AKub|H3K36me3': "broad"
    'H3K27ac|H3K4me3|H3K9ac|H4K16ac|H3K23ac|MNase': "narrow"
    'H3|H4': "broad"
  params: "--keep-dup 'all' --nomodel"
 
# RNA parameters
rna_tracks:
  RNAseq:
    fileorder: "rnaseq"
    param_bg: "--outWigType bedGraph"
    strandedness: "reverse"
    multimap: "multiple" # change to 'unique' if you only want uniquely mapped reads
  RAMPAGE:
    fileorder: "rampage"
    param_bg: "--outWigType bedGraph read1_5p"
    strandedness: "forward"
    multimap: "multiple" # change to 'unique' if you only want uniquely mapped reads

# WGBS parameters
mC_method: "WGBS" # default works for WGBS, replace with Pico or EMSeq when appropriate
mC_context: "all" # another option should be set for CG-only (changes parameters for methylation extraction step)

# If using the Pico or EMseq kit for DNA methylation, trimming parameters should be changed "-u 10 -q 10 -m 20" for SE and "-u 10 -U 10 -q 10 -m 20" ## Can be added as an option based on "sample" name and PE
mC_mapping:
  default: 
    map_pe: "--maxins 1000"
    map_se: ""
    process_pe: "--ignore_r2 2 --buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup
  WGBS: 
    map_pe: "--maxins 1000"
    map_se: ""
    process_pe: "--ignore_r2 2 --buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup
  EMseq:
    map_pe: "--maxins 1000"
    map_se: ""
    process_pe: "--buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup
  Pico:
    map_pe: "--maxins 1000 --non_directional"
    map_se: "--non_directional"
    process_pe: "--buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup

# Analysis parameters
analysis:
  mark_of_interest: "H3K27ac"  # Default histone mark to focus on
  perform_analysis: true       # Whether to perform the complete analysis
  perform_combined: true       # Whether to perform combined analysis per line
  perform_heatmaps: true       # Whether to generate heatmaps with deeptools
  perform_te_analysis: false   # Whether to perform TE analysis (takes long time)

# Resource allocation
standard_resources: &standard
  threads: 4
  mem: 2000
  tmp: 2000

heavy_resources: &heavy
  threads: 16
  mem: 8000
  tmp: 16000

single_thread: &single
  threads: 1
  mem: 8000
  tmp: 16000
  
resources:
  use_pigz: *standard
  chrom_sizes: *single
  region_file: *standard
  fastq_dump: *heavy
  process_fastq: *heavy
  fastqc: *single
  bt2_indices: *heavy
  bt2_map: *heavy
  filter_chip: *heavy
  make_coverage_chip: *heavy 
  make_bigwig_chip: *heavy
  make_fingerprint_plot: *heavy
  macs2: *heavy
  idr: *single
  merging_chip_replicates: *heavy
  making_pseudo_replicates: *heavy
  best_peaks_pseudoreps: *standard
  STAR_indices: *heavy
  STAR_map: *heavy
  filter_rna: *heavy
  bismark_indices: *heavy
  bismark_map: *heavy
  mc_bigwig: *single
  merging_mc_replicates: *heavy
  call_dmrs: *heavy

