name: epigeneticbutton
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python packages (from conda-forge)
  - python=3.8  # Critical for compatibility
  - snakemake>=7.0  # Minimum version for features we need
  - pandas>=1.3
  - pyyaml>=6.0

  # Core bioinformatics tools (from bioconda)
  - bedtools>=2.29
  - bowtie2>=2.4
  - cutadapt>=2.10
  - deeptools>=3.5
  - fastqc>=0.11
  - homer>=4.11
  - idr>=2.0
  - macs2>=2.2
  - meme>=5.3
  - multiqc>=1.11
  - sra-tools>=2.11
  - samtools>=1.10
  - seqkit>=0.13
  - shortstack>=3.8
  - star>=2.7

  # UCSC tools (from bioconda)
  - ucsc-bigwigtobedgraph
  - ucsc-bedgraphtobigwig

  # Utilities (from conda-forge)
  - pigz>=2.3
  - wget>=1.20

  # R and R packages (from conda-forge)
  - r-base=4.0  # Critical for R package compatibility
  - r-dplyr>=1.0
  - r-tidyr>=1.1
  - r-ggplot2>=3.3
  - r-cowplot>=1.1
  - r-rcolorbrewer>=1.1
  - r-purrr>=0.3
  - r-stringr>=1.4
  - r-complexupset>=1.2

  # Bioconductor packages (from bioconda)
  - bioconductor-annotationforge>=1.32
  - bioconductor-rrvgo
  - bioconductor-topgo>=2.42
  - bioconductor-limma>=3.46
  - bioconductor-edger>=3.32 