# Path to the working directory where the repository was cloned
repo_folder: "/grid/martienssen/home/jcahn/nlsas/projects/fpicbutton"
repo_folder_rule: "path/to/epigeneticbutton/repo"

# Name of the run
analysis_name: "test_smk"

# Path to the sample metadata file
sample_file: "config/RNA_samples.tsv"

# Path to the directory containing reference genomes
ref_path: "/grid/martienssen/home/jcahn/nlsas/Genomes/Arabidopsis"
ref_path_rule: "path/to/reference/genomes"

# Output options: "all": returns all QC, stats, plots and files (i.e fastqc, fingerprints, idr, stats table and plots); "none" if you don't want the fastqc; other options can be added.
full_analysis: true
QC_option: "none" # options: ["none"|"all"]

# Species-dependent parameters:
species: "thaliana" #options below or create a new entry with corresponding information

thaliana:
  star_index: "--genomeSAindexNbases 12"
  genomesize: 1.3e8
  ncbiID: "3702" 
  genus: "Arabidopsis"
  go_database: org.Athaliana.eg.db

mays: 
  star_index: "--genomeSAindexNbases 14"
  genomesize: 2.2e9
  ncbiID: "4577"
  genus: "Zea"
  go_database: org.Zmays.eg.db

# Trimming and processing parameters:
trimming_quality:
  ChIP: "-q 10 -m 20"
  RNA: "-q 10 -m 20"
  TF: "-q 10 -m 20"
  mC: "-q 10 -m 20"
  sRNA: "-q 10 -m 15"

adapter1:
  ChIP: "AGATCGGAAGAGCACACGTCTGAAC" # default illumina
  RNA: "AGATCGGAAGAGCACACGTCTGAAC" # default illumina
  TF: "AGATCGGAAGAGCACACGTCTGAAC" # default illumina
  mC: "AGATCGGAAGAGCACACGTCTGAAC" # default illumina
  sRNA: "TGGAATTCTCGGGTGCCAAGG" # default nextflex

# Mapping option default
chip_mapping_option: "default"

# ChIP-seq parameters
# For mapping
chip_mapping:
  default:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeat:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -q 10 -F 256"
  repeatall:
    map_pe: "--very-sensitive --no-mixed --no-discordant --k 100 --end-to-end"
    map_se: "--very-sensitive --k 100 --end-to-end"
    filter: "-b -h -F 256"
  all:
    map_pe: "--end-to-end --maxins 1500"
    map_se: "--end-to-end "
    filter: "-b -h -F 256"

# For bigwigs
chip_tracks:
  binsize: 1
  params: "--scaleFactorsMethod 'None' --normalizeUsing CPM --extendReads 300"

# For peaks
chip_callpeaks:
  # To link the type of IP with the type of peaks. Can be updated with other marks. If creating regex patterns, make sure to escape "." with "\."
  peaktype:
    'H3K4me1|H3K27me1|H3K27me2|H3K27me3|H3K9me1|H3K9me2|H3K9me3|H4K20me1|H4K20me2|H4K20me3|.*DDM1|H3\.3|H3\.1|MGH3|CenH3|PolIIS2P|H2AT120Ph|H2AKub|H3K36me3': "broad"
    'H3K27ac|H3K4me3|H3K9ac|H4K16ac|H3K23ac|MNase': "narrow" 
    'H3|H4': "broad"
  params: "--keep-dup 'all' --nomodel"
 
# RNA parameters
rna_tracks:
  RNAseq:
    file_order: "rnaseq"
    param_bg: "--outWigType bedGraph"
    strandedness: "reverse"
    multimap: "multiple" # change to 'unique' if you only want uniquely mapped reads
  RAMPAGE:
    file_order: "rampage"
    param_bg: "--outWigType bedGraph read1_5p"
    strandedness: "forward"
    multimap: "multiple" # change to 'unique' if you only want uniquely mapped reads

# WGBS parameters
mC_method: "WGBS" # default works for WGBS, replace with Pico or EMSeq when appropriate
mC_context: "all" # another option should be set for CG-only (changes parameters for methylation extraction step)

# If using the Pico or EMseq kit for DNA methylation, trimming parameters should be changed "-u 10 -q 10 -m 20" for SE and "-u 10 -U 10 -q 10 -m 20" ## Can be added as an option based on "sample" name and PE
mC_mapping:
  default: 
    map_pe: "--maxins 1000"
    map_se: ""
    process_pe: "--ignore_r2 2 --buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup
  WGBS: 
    map_pe: "--maxins 1000"
    map_se: ""
    process_pe: "--ignore_r2 2 --buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup
  EMseq:
    map_pe: "--maxins 1000"
    map_se: ""
    process_pe: "--buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup
  Pico:
    map_pe: "--maxins 1000 --non_directional"
    map_se: "--non_directional"
    process_pe: "--buffer_size 16G" # change buffer size if not appropriate for setup
    process_se: "--buffer_size 16G" # change buffer size if not appropriate for setup

# small RNA parameters
structural_rna_depletion: true # to filter structural RNA (rRNAs, tRNAs, snoRNAs) before mapping. Recommended step when studying microRNAs and small interfering RNAs.
structural_rna_fafile: "data/zm_structural_RNAs.fa.gz" # default to structural RNAs from Zea mays present in data directory, prepared through Rfam (see corresponding Help)
srna_mapping_params: "--mmap u --dicermin 21 --dicermax 24 --dn_mirna --no_bigwigs" # consider replacing --dn_mirna with --known_miRNAs KNOWN_MIRNAS.fa (fetching miRNAs sequences from miRBase)
srna_min_size: 21 # these sizes in nucleotide will be used for filtering bigiwg and creating an individual file for each nucleotide size in between (e.g. 20 21 22 23 24)
srna_max_size: 24 # these sizes in nucleotide will be used for filtering bigiwg and creating an individual file for each nucleotide size in between (e.g. 20 21 22 23 24)

# Gene Ontology files to create a new database (make sure you match the reference genome(s) present in the samplefile)
GO: false # If switching to true, make sure the database is created, or the required files below are edited
gaf_file:
  ColCEN: "data/ColCEN_infoGO.tab.gz" # can be gzipped or not
  B73_v5: "data/B73_v5_infoGO.tab.gz" # can be gzipped or not

gene_info_file:
  ColCEN: "data/ColCEN_genes_info.tab.gz" # can be gzipped or not
  B73_v5: "data/B73_v5_genes_info.tab.gz" # can be gzipped or not

# For TF motifs analysis using meme
motifs: true # change to false for motifs on final selected peaks
allreps: false # change to true for motifs analysis on all single replicates
jaspar_db: "data/JASPAR2024_CORE_plants_non-redundant_pfms_meme.txt" # other databases can be downloaded at https://jaspar.elixir.no/downloads/

# optional targets for extra output
motif_target_file_label: "target_motifs" # This name will be used for the name of the results files and should used in the rule target.
motif_target_file: "data/target_genes.bed" # should be a tab-delimited file listing genes in rows where the first column is GID (matching the gene IDs in the reference genome gff) and optionally the second column are labels (see example). Other columns will be ignored. Replace with actual file of target genes, and potentially update the label below too.
motif_ref_genome: "ColCEN" # reference genome to use to extract fasta; safer if a run with this reference genome as already been created; will be treated like the ref_genome of a sample, creating a fasta file in the genomes/<ref_genome> directory if a fasta file is found at ref_path 

rnaseq_target_file_label: "target_genes" # This name will be used for the name of the results files and should used in the rule target.
rnaseq_target_file: "data/target_genes.txt" # should be a tab-delimited file listing genes in rows where the first column is GID (matching the gene IDs in the reference genome gff) and optionally the second column are labels (see example). Other columns will be ignored. Replace with actual file of target genes, and potentially update the label below too.
rnaseq_background_file: "default" # should be a column of GID (matching the gene IDs in the reference genome gff). Other columns will be ignored. Will be used as background for GO enrichment analysis. Default is all genes.

srna_target_file: "config/ath.gff3" # Replace with another file of target genes if sRNA should be performed on other loci. It will be used as LOCIFILE in ShortStack (Can be simple tab-delimited, .bed, or .gff3. Tab-delimited format is column 1 with coordinates Chr:start-stop, column 2 with names. Input file assumed to be simple tab-delimited unless file name ends in .bed or .gff3.)
srna_target_file_label: "miRNAs" # This name will be used for the results folder and should be used in the rule target.

# Resource allocation
minimal_resources: &default
  threads: 1
  mem: 32
  tmp: 32

low_resources: &low
  threads: 1
  mem: 1000
  tmp: 1000

standard_resources: &standard
  threads: 4
  mem: 2000
  tmp: 2000

heavy_resources: &heavy
  threads: 8
  mem: 8000
  tmp: 48000

max_resources: &max
  threads: 16
  mem: 10000
  tmp: 96000

single_thread: &single
  threads: 1
  mem: 32000
  tmp: 48000
  
resources:
  # environment_setup
  check_fasta: *standard
  check_gff: *standard
  check_gtf: *standard
  check_chrom_sizes: *single
  prep_region_file: *low
  # sample_download
  get_fastq_pe: *heavy
  get_fastq_se: *heavy
  run_fastqc: *single
  process_fastq_pe: *heavy
  process_fastq_se: *heavy
  # ChIPseq
  make_bt2_indices: *heavy
  bowtie2_map_pe: *heavy
  bowtie2_map_se: *heavy
  filter_chip_pe: *heavy
  filter_chip_se: *heavy
  make_chip_stats_pe: *low
  make_chip_stats_se: *low
  make_coverage_chip: *heavy 
  make_bigwig_chip: *heavy
  make_fingerprint_plot: *heavy
  calling_peaks_macs2_pe: *heavy
  calling_peaks_macs2_se: *heavy
  idr_analysis_replicates: *single
  merging_chip_replicates: *heavy
  making_pseudo_replicates: *heavy
  best_peaks_pseudoreps: *low
  find_motifs_in_file: *heavy
  make_peak_stats: *low
  # mC
  make_bismark_indices: *heavy
  bismark_map_pe: *max
  bismark_map_se: *max
  make_mc_stats_pe: *low
  make_mc_stats_se: *low
  merging_mc_replicates: *heavy
  make_mc_bigwig_files: *single
  call_DMRs_pairwise: *max
  # RNAseq
  make_STAR_indices: *heavy
  STAR_map_pe: *heavy
  STAR_map_se: *heavy
  filter_rna_pe: *heavy
  filter_rna_se: *heavy
  make_rna_stats_pe: *low
  make_rna_stats_se: *low
  merging_rna_replicates: *heavy
  make_rna_stranded_bigwigs: *heavy
  prep_files_for_DEGs: *single
  call_all_DEGs: *single
  gather_gene_expression_rpkm: *single
  plot_expression_levels: *single
  create_GO_database: *single
  perform_GO_on_target_file: *single
  # smallRNA
  shortstack_map: *heavy
  filter_structural_rna: *heavy
  shortstack_map: *heavy
  make_srna_size_stats: *standard
  filter_size_srna_sample: *standard
  merging_srna_replicates: *standard
  make_srna_stranded_bigwigs: *standard
  analyze_all_srna_samples_on_target_file: *heavy
  prep_files_for_differential_srna_clusters: *single
  call_all_differential_srna_clusters: *single
  # combined_analysis
  prepping_mapping_stats: *low
  plotting_mapping_stats: *low
  prepping_chip_peak_stats: *low
  plotting_peaks_stats_chip_tf: *low
  prepping_srna_sizes_stats: *low
  plotting_srna_sizes_stats: *low
  combine_peakfiles: *low
  get_annotations_for_bedfile: *low
  plotting_upset_peaks: *low