# profiles/geno/config.yaml
executor: slurm
jobs: 16
use-conda: true
conda-frontend: conda
conda-cleanup-pkgs: tarballs
latency-wait: 60
max-jobs-per-second: 2
max-status-checks-per-second: 5

# Resource allocation
low_resources: &low
  mem_mb: 1000
  tmp_mb: 1000
  runtime: "1h"

standard_resources: &standard
  mem_mb: 2000
  tmp_mb: 2000
  runtime: "2h"

download_resources: &download
  mem_mb: 4000
  tmp_mb: 16000
  runtime: "12h"

heavy_resources: &heavy
  mem_mb: 8000
  tmp_mb: 16000
  runtime: "8h"

heavier_resources: &heavier
  mem_mb: 12000
  tmp_mb: 32000
  runtime: "8h"
  
max_resources: &max
  mem_mb: 24000
  tmp_mb: 32000
  runtime: "2d"

single_thread: &single
  mem_mb: 8000
  tmp_mb: 16000
  runtime: "8h"

set-threads:
  bismark_map_pe: 6
  bismark_map_se: 6
  
set-resources:
# Environment setup
  check_fasta: *download
  check_gff: *download
  check_gtf: *standard
  check_chrom_sizes: *low
  compute_genome_stats: *low
  resolve_taxid: *single
  prep_region_file: *low
  check_te_file: *download
# Sample download
  get_fastq_pe: *download
  get_fastq_se: *download
  run_fastqc: *single
  process_fastq_pe: *heavy
  process_fastq_se: *heavy
  get_available_bam: *standard
# ChIPseq
  make_bt2_indices: *heavy
  make_chromap_index: *heavy
  filter_bam_pe: *heavier
  filter_bam_se: *heavier
  make_mapping_stats_pe: *low
  make_mapping_stats_se: *low
  dispatch_final_bam: *standard
  make_coverage_chip: *heavy
  make_bigwig_chip: *heavy
  make_fingerprint_plot: *heavy
  calling_peaks_macs2_pe: *heavy
  calling_peaks_macs2_se: *heavy
  idr_analysis_replicates: *single
  merging_bam_replicates: *heavy
  making_pseudo_replicates: *heavy
  best_peaks_pseudoreps: *low
  find_motifs_in_file: *heavy
  make_peak_stats: *low
  perform_pairwise_diff_peaks: *heavy
# ATACseq
  atac_shift_bam: *standard
  atac_bam_to_bed: *low
  calling_peaks_atac: *heavy
  make_coverage_atac: *heavier
# mC / dmC
  make_bismark_indices: *heavy
  bismark_map_pe: *max
  bismark_map_se: *max
  make_mc_stats_pe: *low
  make_mc_stats_se: *low
  merging_mc_replicates: *heavy
  make_mc_bigwig_files: *single
  call_DMRs_pairwise: *max
  make_modkit_context_beds: *heavy
  get_modbam: *download
  get_bedmethyl: *low
  align_modbam: *max
  modkit_summary: *heavy
  modkit_pileup: *heavy
  split_bedmethyl_by_context: *heavy
  make_dmc_bigwig_files: *single
  call_DMRs_modkit: *max
  convert_bedmethyl_to_cx_report: *standard
# Combined analysis
  prepping_mapping_stats: *low
  plotting_mapping_stats: *low
  prepping_peak_stats: *low
  plotting_peak_stats: *low
  combine_peakfiles: *low
  get_annotations_for_bedfile: *low
  plotting_upset_regions: *low
  making_stranded_matrix_on_targetfile: *heavy
  merging_matrix: *single
  computing_matrix_scales: *single
  sort_heatmap: *single
  plotting_heatmap_on_targetfile: *single
  plotting_sorted_heatmap_on_targetfile: *single
  plotting_profile_on_targetfile: *single
  prep_chromosomes_for_browser: *low
  prep_browser_on_region: *heavy
  make_single_loci_browser_plot: *single
  merge_region_browser_plots: *low
  summarize_tracks_pca: *max
  plot_PCA_correlation: *single
