# profiles/slurm/config.yaml
executor: slurm
jobs: 16
use-conda: true
conda-frontend: conda
latency-wait: 60
restart-times: 1

sbatch:
  job-name: "smk_{jobid}"
  cpus-per-task: "{threads}"
  mem: "{resources.mem_mb}"
  qos: "{resources.qos}"
  output: "hpclogs/{rule}/smk_{jobid}.log"
  error: "hpclogs/{rule}/smk_{jobid}.log"