# profiles/slurm/config.yaml
jobs: 16
use-conda: true
conda-frontend: conda
latency-wait: 60
restart-times: 1

cluster-config: ../cluster.yaml

cluster: >-
  sbatch
  --job-name=smk_{jobid}
  --cpus-per-task={threads}
  --mem={cluster.mem_mb}
  --output=hpclogs/{rule}/smk_{jobid}.log
  --error=hpclogs/{rule}/smk_{jobid}.log
  --qos={cluster.qos}
